In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

STEP 1: LOAD DATASET

In [ ]:
df=pd.read_csv("student_performance_dataset.csv")
print("First 5 rows of the dataset")
df.head()

First 5 rows of the dataset

,Student_ID,Gender,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score,Pass_Fail
0,S147,Male,31,68.267841,86,High School,Yes,Yes,63,Pass
1,S136,Male,16,78.222927,73,PhD,No,No,50,Fail
2,S209,Female,21,87.525096,74,PhD,Yes,No,55,Fail
3,S458,Female,27,92.076483,99,Bachelors,No,No,65,Pass
4,S078,Female,37,98.655517,63,Masters,No,Yes,70,Pass

In [ ]:
print("\nStatistical Summary:")
df.describe()

Statistical Summary:

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Final_Exam_Score
count,708.000000,708.000000,708.000000,708.000000
mean,26.132768,78.107722,77.871469,58.771186
std,8.877727,13.802802,14.402739,6.705877
min,10.000000,50.116970,50.000000,50.000000
25%,19.000000,67.550094,65.000000,52.000000
50%,27.000000,79.363046,79.000000,59.500000
75%,34.000000,89.504232,91.000000,64.000000
max,39.000000,99.967675,100.000000,77.000000

STEP2: ARTIFICIALLY INSERT A FEW OUTLIERS

In [ ]:
num_cols=['Study_Hours_per_Week','Attendance_Rate','Past_Exam_Scores','Final_Exam_Score']
df.loc[1,"Attendance_Rate"]=250
df.loc[0,"Study_Hours_per_Week"]=120
df.loc[2,"Past_Exam_Scores"]=-20
df.loc[3,"Final_Exam_Score"]=200
print("\nInserted a few artificial outliers for demonstartion.")

Inserted a few artificial outliers for demonstartion.

STEP 3: OUTLIER DETECTION USING IQR METHOD

In [ ]:
print("\n----- IQR METHOD -----")
for col in num_cols:
  q3=df[col].quantile(0.75)
  q1=df[col].quantile(0.25)
  IQR=q3-q1
  lower=q1-1.5 * IQR
  upper=q3+1.5 * IQR

  outliers=df[(df[col]<lower) | (df[col]>upper)]
  print(f"{col}:{len(outliers)} outlier(s) found (limits: {lower:.2f} to {upper:.2f})")

----- IQR METHOD -----
Study_Hours_per_Week:1 outlier(s) found (limits: -3.50 to 56.50)
Attendance_Rate:1 outlier(s) found (limits: 34.62 to 122.44)
Past_Exam_Scores:1 outlier(s) found (limits: 26.00 to 130.00)
Final_Exam_Score:1 outlier(s) found (limits: 34.00 to 82.00)

STEP 4:OUTLIER DETECTION USING Z-SCORE METHOD

In [ ]:
print("\n----- Z-SCORE METHOD -----")
for col in num_cols:
  z_scores=(df[col]-df[col].mean())/ df[col].std()
  outliers=df[z_scores.abs()>3]
  print(f"{col}:{len(outliers)} outlier(s) found (|z| > 3)")

----- Z-SCORE METHOD -----
Study_Hours_per_Week:1 outlier(s) found (|z| > 3)
Attendance_Rate:1 outlier(s) found (|z| > 3)
Past_Exam_Scores:1 outlier(s) found (|z| > 3)
Final_Exam_Score:1 outlier(s) found (|z| > 3)

STEP 5: TREAT OUTLIERS (CAP THEM TO THE IQR LIMITS)

In [ ]:
df_treated=df.copy()
for col in num_cols:
  q1=df_treated[col].quantile(0.25)
  q3=df_treated[col].quantile(0.75)
  IQR=q3-q1
  lower=q1-1.5*IQR
  upper=q3+1.5*IQR

  df_treated[col]=df_treated[col].clip(lower,upper)
  print(f"{col}: values capped between {lower:.2f} and {upper:.2f}")

Study_Hours_per_Week: values capped between -3.50 and 56.50
Attendance_Rate: values capped between 34.62 and 122.44
Past_Exam_Scores: values capped between 26.00 and 130.00
Final_Exam_Score: values capped between 34.00 and 82.00

STEP 6: COMPARE STATISTICS BEFORE AND AFTER

In [ ]:
print("\nStatistical BEFORE treatment:")
df[num_cols].describe()

Statistical BEFORE treatment:

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Final_Exam_Score
count,708.000000,708.000000,708.000000,708.000000
mean,26.258475,78.350345,77.738701,58.961864
std,9.551298,15.239763,14.864340,8.549214
min,10.000000,50.116970,-20.000000,50.000000
25%,19.000000,67.550094,65.000000,52.000000
50%,27.000000,79.372680,79.000000,59.500000
75%,34.000000,89.504232,91.000000,64.000000
max,120.000000,250.000000,100.000000,200.000000

In [ ]:
print("\nStatistical AFTER treatment:")
df_treated[num_cols].describe()

Statistical AFTER treatment:

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Final_Exam_Score
count,708.000000,708.000000,708.000000,708.000000
mean,26.168785,78.170169,77.803672,58.795198
std,8.948942,13.902974,14.533369,6.758441
min,10.000000,50.116970,26.000000,50.000000
25%,19.000000,67.550094,65.000000,52.000000
50%,27.000000,79.372680,79.000000,59.500000
75%,34.000000,89.504232,91.000000,64.000000
max,56.500000,122.435439,100.000000,82.000000

STEP 7: SAVE THE CLEANED DATASET

In [ ]:
df_treated.to_csv("student_performance_dataset_treated.csv",index=False)
print("\nTreated dataset saved as 'student_performance_dataset_treated.csv'")
print("Program executed successfully.")

Treated dataset saved as 'student_performance_dataset_treated.csv'
Program executed successfully.